# Generated by Django 3.2.9 on 2021-12-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211221_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiafilmCollection',
        ),
    ]
