# Generated by Django 3.2.10 on 2021-12-30 23:31

import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
from django.db import migrations, models

import core.blocks.content
import core.blocks.specific
import core.blocks.text


class Migration(migrations.Migration):

    dependencies = [
        # ('wagtailsvg', '0004_alter_svg_file'),
        ('core', '0006_diafilmcollection'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='diafilmpage',
        #     name='title_image',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg', verbose_name='Название картинкой'),
        # ),
    ]
