# Generated by Django 3.2.9 on 2022-01-24 22:52

import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
from django.db import migrations, models

import core.blocks.content
import core.blocks.specific
import core.blocks.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211231_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Диафильмов'),
        ),
    ]
